name: Sysdig Image Scan

on:
    push:
          branches:
                  - main
                      pull_request:
                            branches:
                                    - main

                            jobs:
                                sysdig-scan:
                                      runs-on: ubuntu-latest

                                            steps:
                                                  - name: Check out code
                                                          uses: actions/checkout@v2

                                                                - name: Install Sysdig CLI
                                                                        run: curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | bash

                                                                              - name: Sysdig Image Scan
                                                                                      env:
                                                                                                SYSDIG_API_TOKEN: ${{ secrets.SYSDIG_API_TOKEN }}
                                                                                                        run: sysdig secure image scan --address https://secure.sysdig.com --no-prompts <IMAGE_NAME>:<TAG>
                                                                                                          
